/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.google.example.java-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
    implementation("ch.qos.logback:logback-classic")
    implementation("org.slf4j:slf4j-api")
    implementation("org.slf4j:jul-to-slf4j")
}

application {
    // Define the main class for the application.
    mainClass.set("com.google.example.app.App")
}