/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.google.example.app;

import java.util.logging.Logger;
import java.net.http.HttpClient;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;

public class App {
    private static final Logger log = Logger.getLogger(App.class.getName());

    public static void main(String[] args) throws java.io.IOException, InterruptedException {
        com.google.example.utilities.Logging.initializeLogging();
        log.info("Performing batch job work.");

        String service = System.getenv("SERVICE_NAME");

        HttpClient httpClient = HttpClient.newHttpClient();
        HttpResponse<String> response = httpClient.send(java.net.http.HttpRequest.newBuilder()
            .uri(java.net.URI.create(service))
            .timeout(java.time.Duration.ofMinutes(2))
            .GET()
            .build(), BodyHandlers.ofString());
        log.info("Processing complete, status: " + response.statusCode());
    }

}
