name: "YAML lint"

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Yamllint Github Action
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_config_filepath: ./.github/workflows/config/yamllint.yaml
